# Generated by Django 4.0.3 on 2022-03-06 07:45

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='KZ', unique=True, verbose_name='Номер телефона'),
        ),
    ]
