# Generated by Django 4.0.3 on 2022-03-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('they', 'Не задано'), ('woman', 'Женщина'), ('man', 'Мужчина')], max_length=20, null=True, verbose_name='Пол'),
        ),
    ]
