# Generated by Django 4.0 on 2022-03-09 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_alter_post_text'),
        ('instagram', '0002_comment'),
    ]

    operations = [
    ]
