# Generated by Django 3.2.9 on 2022-03-10 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_post_post_likes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set(),
        ),
    ]
